In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [10]:
DeathRate = pd.read_excel('../data/death.xlsx')

In [11]:
DeathRate

,County,FIPS,Met Healthy People Objective of 15.3?,"Age-Adjusted Death Rate([rate note]) - deaths per 100,000",Lower CI (Rate),Upper CI (Rate),CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Death Rates,Lower 95% Confidence Interval,Upper 95% Confidence Interval
0,Tennessee,47000,No,21.6,21,22.2,N/A,2,16,978,falling,-1.4,-1.6,-1.2
1,United States,0,No,19.6,19.5,19.7,N/A,N/A,N/A,42101,falling,-1.3,-1.4,-1.1
2,Crockett County,47033,No,31.9,17.3,54.4,1,1,69,3,*,*,*,*
3,Unicoi County,47171,No,31.7,19.6,49.9,2,1,66,5,*,*,*,*
4,Scott County,47151,No,31.3,19.5,48,3,1,68,5,stable,0.8,-0.8,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Smith County,47159,***,*,*,*,*,*,*,3 or fewer,*,*,*,*
93,Stewart County,47161,***,*,*,*,*,*,*,3 or fewer,*,*,*,*
94,Trousdale County,47169,***,*,*,*,*,*,*,3 or fewer,*,*,*,*
95,Van Buren County,47175,***,*,*,*,*,*,*,3 or fewer,*,*,*,*
96,Wayne County,47181,***,*,*,*,*,*,*,3 or fewer,*,*,*,*

In [17]:
HealthIns_16 = pd.read_excel('../data/Health_Economics_2016.xlsx', sheet_name =('Data'))

In [18]:
HealthIns_16

,Unnamed: 0,"Anderson County, Tennessee",Unnamed: 2,Unnamed: 3,Unnamed: 4,"Bedford County, Tennessee",Unnamed: 6,Unnamed: 7,Unnamed: 8,"Benton County, Tennessee",...,Unnamed: 375,Unnamed: 376,"Wilson County, Tennessee",Unnamed: 378,Unnamed: 379,Unnamed: 380,Tennessee,Unnamed: 382,Unnamed: 383,Unnamed: 384
0,Label,Estimate,Margin of Error,Percent,Percent Margin of Error,Estimate,Margin of Error,Percent,Percent Margin of Error,Estimate,...,Percent,Percent Margin of Error,Estimate,Margin of Error,Percent,Percent Margin of Error,Estimate,Margin of Error,Percent,Percent Margin of Error
1,EMPLOYMENT STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Population 16 years and over,"61,370",Â±218,"61,370",(X),"35,524",Â±146,"35,524",(X),"13,464",...,"154,525",(X),"98,754",Â±250,"98,754",(X),"5,222,438","Â±2,062","5,222,438",(X)
3,In labor force,"34,409",Â±765,56.1%,Â±1.3,"22,265",Â±699,62.7%,Â±2.0,"6,632",...,68.8%,Â±0.7,"64,645","Â±1,056",65.5%,Â±1.1,"3,193,436","Â±7,364",61.1%,Â±0.1
4,Civilian labor force,"34,409",Â±765,56.1%,Â±1.3,"22,247",Â±701,62.6%,Â±2.0,"6,632",...,68.8%,Â±0.7,"64,495","Â±1,066",65.3%,Â±1.1,"3,175,503","Â±7,251",60.8%,Â±0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,18 years and over,(X),(X),14.4%,Â±1.1,(X),(X),14.0%,Â±1.9,(X),...,4.7%,Â±0.5,(X),(X),8.0%,Â±0.9,(X),(X),14.9%,Â±0.2
142,18 to 64 years,(X),(X),16.4%,Â±1.4,(X),(X),15.6%,Â±2.3,(X),...,4.7%,Â±0.5,(X),(X),8.5%,Â±1.1,(X),(X),16.1%,Â±0.2
143,65 years and over,(X),(X),8.0%,Â±1.6,(X),(X),7.4%,Â±2.1,(X),...,4.6%,Â±1.1,(X),(X),5.8%,Â±1.2,(X),(X),9.7%,Â±0.2
144,People in families,(X),(X),15.1%,Â±1.8,(X),(X),14.0%,Â±2.5,(X),...,4.0%,Â±0.6,(X),(X),7.2%,Â±0.9,(X),(X),14.6%,Â±0.2
145,Unrelated individuals 15 years and over,(X),(X),26.0%,Â±2.9,(X),(X),29.8%,Â±5.1,(X),...,16.4%,Â±2.1,(X),(X),21.5%,Â±2.9,(X),(X),29.0%,Â±0.3