In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
death_rate = pd.read_csv('../data/2015-2020 death.csv')

In [3]:
death_rate

,County,FIPS,Met Healthy People Objective of 15.3?,"Age-Adjusted Death Rate([rate note]) - deaths per 100,000",Race,Lower CI (Rate),Upper CI (Rate),CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Death Rates,Lower 95% Confidence Interval,Upper 95% Confidence Interval
0,Tennessee,47000,No,21.6,All races,21,22.2,N/A,2,16,978,falling,-1.4,-1.6,-1.2
1,United States,0,No,19.6,All races,19.5,19.7,N/A,N/A,N/A,42101,falling,-1.3,-1.4,-1.1
2,Crockett County,47033,No,31.9,All races,17.3,54.4,1,1,69,3,*,*,*,*
3,Unicoi County,47171,No,31.7,All races,19.6,49.9,2,1,66,5,*,*,*,*
4,Scott County,47151,No,31.3,All races,19.5,48,3,1,68,5,stable,0.8,-0.8,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Wayne County,47181,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
287,Weakley County,47183,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
288,White County,47185,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
289,Williamson County,47187,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
290,Wilson County,47189,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*

In [4]:
death_rate = death_rate.rename(columns={'Age-Adjusted Death Rate([rate note]) - deaths per 100,000' : 'Age-Adjusted Death Rate'})

In [5]:
death_rate

,County,FIPS,Met Healthy People Objective of 15.3?,Age-Adjusted Death Rate,Race,Lower CI (Rate),Upper CI (Rate),CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Death Rates,Lower 95% Confidence Interval,Upper 95% Confidence Interval
0,Tennessee,47000,No,21.6,All races,21,22.2,N/A,2,16,978,falling,-1.4,-1.6,-1.2
1,United States,0,No,19.6,All races,19.5,19.7,N/A,N/A,N/A,42101,falling,-1.3,-1.4,-1.1
2,Crockett County,47033,No,31.9,All races,17.3,54.4,1,1,69,3,*,*,*,*
3,Unicoi County,47171,No,31.7,All races,19.6,49.9,2,1,66,5,*,*,*,*
4,Scott County,47151,No,31.3,All races,19.5,48,3,1,68,5,stable,0.8,-0.8,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Wayne County,47181,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
287,Weakley County,47183,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
288,White County,47185,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
289,Williamson County,47187,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
290,Wilson County,47189,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*

In [6]:
death_rate = death_rate.rename(columns={'County' : 'county'})

In [7]:
death_rate

,county,FIPS,Met Healthy People Objective of 15.3?,Age-Adjusted Death Rate,Race,Lower CI (Rate),Upper CI (Rate),CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Death Rates,Lower 95% Confidence Interval,Upper 95% Confidence Interval
0,Tennessee,47000,No,21.6,All races,21,22.2,N/A,2,16,978,falling,-1.4,-1.6,-1.2
1,United States,0,No,19.6,All races,19.5,19.7,N/A,N/A,N/A,42101,falling,-1.3,-1.4,-1.1
2,Crockett County,47033,No,31.9,All races,17.3,54.4,1,1,69,3,*,*,*,*
3,Unicoi County,47171,No,31.7,All races,19.6,49.9,2,1,66,5,*,*,*,*
4,Scott County,47151,No,31.3,All races,19.5,48,3,1,68,5,stable,0.8,-0.8,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Wayne County,47181,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
287,Weakley County,47183,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
288,White County,47185,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
289,Williamson County,47187,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*
290,Wilson County,47189,***,NaN,Black,*,*,*,*,*,3 or fewer,*,*,*,*

animals_slaughtered.rename(columns={"" : ""})

In [8]:
insurance = pd.read_csv('../data/acs-2015-2020.csv')

In [9]:
insurance

,county,Year,EMPLOYMENT STATS - Ages 16 yrs+,EMPLOYMENT STATS - Ages 16 yrs+ - In labor force,EMPLOYMENTSTATS - Ages 16 yrs+ - In labor force,EMPLOYMENTSTATS - Ages 16 yrs+ - In labor force(Civilian),EMPLOYMENTSTATS - Ages 16 yrs+ - In labor force(Civilian),EMPLOYMENTSTATS - Ages 16 yrs+ - Employed_In labor force(Civilian),EMPLOYMENTSTATS - Ages 16 yrs+ - Employed_In labor force(Civilian),EMPLOYMENT STATS - Ages 16 yrs+ -Unemployed- In labor force(Civilian),...,HEALTH INSURANCE COVERAGE - Unemployed (With private insurance coverage) Ages 19 to 64 years- In labor force,HEALTH INSURANCE COVERAGE - Unemployed(With public insurance coverage) Ages 19 to 64 years-In labor force,HEALTH INSURANCE COVERAGE - Unemployed(With public insurance coverage) Ages 19 to 64 years-In labor force,HEALTH INSURANCE COVERAGE - Unemployed(No health insurance coverage) Ages 19 to 64 years -In labor force,HEALTH INSURANCE COVERAGE - Unemployed(No health insurance coverage) Ages 19 to 64 years -In labor force,HEALTH INSURANCE COVERAGE - Not in labor force(No health insurance coverage) Ages 19 to 64 years,HEALTH INSURANCE COVERAGE - Not in labor force(No health insurance coverage) Ages 19 to 64 years,GEOID,State,County_Num
0,Meigs County,2020,"10,036","5,162",51.4,"5,162",51.4,"4,702",46.9,460,...,34.0,142,35.8,120,30.2,366,16.3,0500000US47121,47.0,121.0
1,Montgomery County,2020,"155,404","103,722",66.7,"91,222",58.7,"85,780",55.2,"5,442",...,49.8,"1,350",27.7,"1,396",28.6,"2,847",9.6,0500000US47125,47.0,125.0
2,Moore County,2020,"5,321","2,931",55.1,"2,902",54.5,"2,789",52.4,113,...,49.0,18,17.3,35,33.7,138,12.4,0500000US47127,47.0,127.0
3,Obion County,2020,"24,444","13,483",55.2,"13,440",55.0,"12,613",51.6,827,...,26.8,183,24.6,362,48.6,792,16.6,0500000US47131,47.0,131.0
4,Overton County,2020,"17,912","9,898",55.3,"9,897",55.3,"9,545",53.3,352,...,24.3,108,39.7,106,39.0,406,12.4,0500000US47133,47.0,133.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,Bledsoe County,2016,"11,648","5,375",46.1,"5,361",46.0,"4,861",41.7,500,...,23.7,165,36.9,176,39.4,786,29.1,0500000US47007,47.0,7.0
471,Campbell County,2016,"32,827","16,070",49.0,"16,058",48.9,"14,660",44.7,"1,398",...,19.3,368,27.6,727,54.5,"1,810",20.6,0500000US47013,47.0,13.0
472,Cannon County,2016,"11,283","6,558",58.1,"6,532",57.9,"5,885",52.2,647,...,27.4,129,22.4,318,55.1,401,17.6,0500000US47015,47.0,15.0
473,Houston County,2016,"6,603","3,302",50.0,"3,302",50.0,"3,057",46.3,245,...,40.2,47,20.1,93,39.7,350,21.0,0500000US47083,47.0,83.0
474,Maury County,2016,"67,419","42,066",62.4,"41,987",62.3,"39,000",57.8,"2,987",...,31.9,829,30.7,"1,081",40.1,"2,161",16.8,0500000US47119,47.0,119.0

In [10]:
mammogram = pd.read_excel('../data/Mammogram Facilities.xlsx')

In [11]:
mammogram

,facility,phone number,city,zip code,County Name
0,Premier Radiology Antioch,(615) 467-4642,"Antioch, TN",37013,Davidson County
1,Starr Regional Breast Cen,(423) 744-3372 x3373,"Athens, TN",37303,McMinn County
2,Saint Francis Hospital -,(901) 820-7575,"Bartlett, TN",38133,Shelby County
3,Memphis OB/GYN Associatio,(901) 373-9221,"Bartlett, TN",38133,Shelby County
4,West Tennessee Healthcare,(731) 659-0243,"Bolivar, TN",38008,Hardeman County
...,...,...,...,...,...
187,Baptist Memorial Hospital,(731) 884-8550 x8553,"Union City, TN",38261,Obion County
188,Ascension Saint Thomas Th,(931) 296-0298,"Waverly, TN",37185,Humphreys County
189,Wayne Medical Center,(931) 722-5411 x2060,"Waynesboro, TN",38485,Wayne County
190,Woman's Center of STRHS-W,(931) 967-8258,"Winchester, TN",37398,Franklin County
191,Saint Thomas Stones River,(615) 563-7229,"Woodbury, TN",37190,Cannon County

In [12]:
coverage = pd.read_csv('../data/2015-2020_ACS_Insurance.csv',  encoding='cp1252')

In [13]:
coverage

,county,Year,Total population,Total population - Male,Total population - Female,"Total population - Hispanic or Latino, White",Total population - Black or African American,Total population - American Indian & Alaska Native,Total population - Asian,Total population - Native Hawaiian & Other Pacific Islander,...,Percent of Uninsured population - (American Indian and Alaska Native),Percent of Uninsured population - (Asian),Percent of Uninsured population - (Native Hawaiian and Other Pacific Islander),"Percent of Uninsured population - (HISPANIC OR LATINO, (Some other race alone)","Percent of Uninsured population - (HISPANIC OR LATINO, (Two or more races)","Percent of Uninsured population - (HISPANIC OR LATINO, (of any race)",Percent of Uninsured population - (White),GEOID,state,county.1
0,Meigs County,2020,12129,5982,6147,11536,224,45,33,-,...,0.0,0.0,-666666666.0,0.0,0.0,15.8,11.3,0500000US47121,47,121
1,Montgomery County,2020,191007,90431,100576,131487,37619,878,4744,605,...,6.4,8.6,6.6,19.2,8.9,13.8,6.8,0500000US47125,47,125
2,Moore County,2020,6302,3105,3197,5890,91,72,184,1,...,0.0,0.0,0.0,-666666666.0,0.0,-666666666.0,8.4,0500000US47127,47,127
3,Obion County,2020,29900,14372,15528,25021,3322,72,120,5,...,2.8,27.5,0.0,45.1,14.5,24.4,8.1,0500000US47131,47,131
4,Overton County,2020,21876,10700,11176,21214,71,24,70,139,...,0.0,0.0,0.0,100.0,7.4,0.0,9.0,0500000US47133,47,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,Bledsoe County,2016,12884,987,6771,6113,12139,132,108,12,...,0.0,0.0,0.0,-666666666.0,30.0,12.2,47.5,0500000US47007,47,7
471,Campbell County,2016,39509,2957,19329,20180,38655,221,106,84,...,10.4,0.0,0.0,-666666666.0,0.0,13.1,19.7,0500000US47013,47,13
472,Cannon County,2016,13666,1137,6753,6913,13044,169,58,96,...,10.7,0.0,62.5,-666666666.0,100.0,8.2,61.8,0500000US47015,47,15
473,Houston County,2016,8037,580,4025,4012,7589,229,40,22,...,36.2,0.0,100.0,-666666666.0,-666666666.0,3.8,26.7,0500000US47083,47,83
474,Maury County,2016,84594,6653,40622,43972,71206,9749,347,681,...,12.0,25.6,34.2,-666666666.0,29.6,5.0,38.0,0500000US47119,47,119

In [33]:
coverage.columns = coverage.columns.str.strip()

Merging Death Rate with the Coverage DFs to try and create a correlation graph.

In [14]:
death_coverage = death_rate.merge(coverage, on=['county'], how ='outer')

In [15]:
death_coverage

,county,FIPS,Met Healthy People Objective of 15.3?,Age-Adjusted Death Rate,Race,Lower CI (Rate),Upper CI (Rate),CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),...,Percent of Uninsured population - (American Indian and Alaska Native),Percent of Uninsured population - (Asian),Percent of Uninsured population - (Native Hawaiian and Other Pacific Islander),"Percent of Uninsured population - (HISPANIC OR LATINO, (Some other race alone)","Percent of Uninsured population - (HISPANIC OR LATINO, (Two or more races)","Percent of Uninsured population - (HISPANIC OR LATINO, (of any race)",Percent of Uninsured population - (White),GEOID,state,county.1
0,Tennessee,47000,No,21.6,All races,21,22.2,N/A,2,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tennessee,47000,No,20.7,White,20.1,21.4,N/A,4,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tennessee,47000,No,29.1,Black,27.2,31.1,N/A,1,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United States,0,No,19.6,All races,19.5,19.7,N/A,N/A,N/A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States,0,No,27.6,Black,27.3,27.9,N/A,N/A,N/A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1426,Wayne County,47181,***,NaN,Black,*,*,*,*,*,...,0.0,37.1,-666666666.0,0.0,0.0,10.7,12.1,0500000US47181,47.0,181.0
1427,Wayne County,47181,***,NaN,Black,*,*,*,*,*,...,0.0,54.7,-666666666.0,0.0,0.0,9.5,11.4,0500000US47181,47.0,181.0
1428,Wayne County,47181,***,NaN,Black,*,*,*,*,*,...,0.0,62.1,-666666666.0,0.0,0.0,9.7,11.3,0500000US47181,47.0,181.0
1429,Wayne County,47181,***,NaN,Black,*,*,*,*,*,...,15.9,0.0,43.2,-666666666.0,46.8,0.0,23.4,0500000US47181,47.0,181.0
1430,United States (6),0,No,19.7,White,19.6,19.8,N/A,N/A,N/A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
death_coverage.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1431 entries, 0 to 1430
Data columns (total 81 columns):
 #   Column                                                                               Non-Null Count  Dtype
---  ------                                                                               --------------  -----
 0   county                                                                               1431 non-null   object
 1    FIPS                                                                                1431 non-null   int64
 2   Met Healthy People Objective of 15.3?                                                1431 non-null   object
 3   Age-Adjusted Death Rate                                                              711 non-null    float64
 4   Race                                                                                 1431 non-null   object
 5   Lower CI (Rate)                                                                      1431 non-null   object
 6   Upper CI (Rate)                                                                      1431 non-null   object
 7   CI*Rank([rank note])                                                                 1431 non-null   object
 8   Lower CI (CI*Rank)                                                                   1431 non-null   object
 9   Upper CI (CI*Rank)                                                                   1431 non-null   object
 10  Average Annual Count                                                                 1431 non-null   object
 11  Recent Trend                                                                         1431 non-null   object
 12  Recent 5-Year Trend ([trend note]) in Death Rates                                    1431 non-null   object
 13  Lower 95% Confidence Interval                                                        1431 non-null   object
 14  Upper 95% Confidence Interval                                                        1431 non-null   object
 15  Year                                                                                 1425 non-null   float64
 16   Total population                                                                    1425 non-null   float64
 17   Total population - Male                                                             1425 non-null   float64
 18  Total population - Female                                                            1425 non-null   float64
 19  Total population - Hispanic or Latino, White                                         1425 non-null   float64
 20  Total population - Black or African American                                         1425 non-null   object
 21  Total population - American Indian & Alaska Native                                   1425 non-null   object
 22  Total population - Asian                                                             1425 non-null   object
 23   Total population - Native Hawaiian & Other Pacific Islander                         1425 non-null   object
 24  Total population - Some other race alone                                             1425 non-null   object
 25  Total population - Hispanic or Latino, Two or more races                             1425 non-null   object
 26  Total population -Hispanic or Latino (of any race)                                   1425 non-null   object
 27  Total population - White                                                             1425 non-null   float64
 28   Total (General) â€“ Ratio to Poverty (poverty status determined)                      1425 non-null   float64
 29  Total (General) â€“ Ratio to Poverty (Below 100 percent of the poverty threshold)      1425 non-null   float64
 30  Total â€“ Insured Population                                                           1425 non-null   float64
 31  Total â€“ Insured Population (Male)                                                    1425 non-null   float64
 32  Total â€“ Insured Population (Female)                                                  1425 non-null   float64
 33  Total â€“ Insured Population (HISPANIC OR LATINO, White)                               1425 non-null   float64
 34  Total â€“ Insured Population (Black or African American)                               1425 non-null   object
 35  Total â€“ Insured Population (American Indian and Alaska Native)                       1425 non-null   object
 36  Total â€“ Insured Population (Asian)                                                   1425 non-null   object
 37   Total â€“ Insured Population (Native Hawaiian and Other Pacific Islander)             1425 non-null   object
 38   Total â€“ Insured Population (HISPANIC OR LATINO ORIGIN (Some other race alone)       1425 non-null   object
 39  Total â€“ Insured Population (HISPANIC OR LATINO ORIGIN (Two or more races)            1425 non-null   object
 40  Total â€“ Insured Population (HISPANIC OR LATINO ORIGIN (of any race)                  1425 non-null   object
 41  Total â€“ Insured Population (White)                                                   1425 non-null   object
 42   Percent of Insured population                                                       1425 non-null   float64
 43  Percent of Insured population - (Male)                                               1425 non-null   float64
 44  Percent of Insured population - (Female)                                             1425 non-null   float64
 45  Percent of Insured population - (HISPANIC OR LATINO, White)                          1425 non-null   float64
 46  Percent of Insured population - (Black or African American)                          1425 non-null   float64
 47  Percent of Insured population - (American Indian and Alaska Native)                  1425 non-null   float64
 48  Percent of Insured population - (Asian)                                              1425 non-null   float64
 49  Percent of Insured population - (Native Hawaiian and Other Pacific Islander)         1425 non-null   float64
 50  Percent of Insured population - (HISPANIC OR LATINO ORIGIN, (Some other race alone)  1425 non-null   float64
 51  Percent of Insured population - (HISPANIC OR LATINO ORIGIN, (Two or more races)      1425 non-null   float64
 52  Percent of Insured population - (HISPANIC OR LATINO ORIGIN, (of any race)            1425 non-null   float64
 53  Percent of Insured population - (White)                                              1425 non-null   float64
 54  Total â€“ Uninsured Population                                                         1425 non-null   float64
 55  Total â€“ Uninsured Population (Male)                                                  1425 non-null   float64
 56   Total â€“ Uninsured Population (Female)                                               1425 non-null   float64
 57  Total â€“ Uninsured Population (HISPANIC OR LATINO, White)                             1425 non-null   float64
 58  Total â€“ Uninsured Population (Black or African American)                             1425 non-null   object
 59   Total â€“ Uninsured Population (American Indian and Alaska Native)                    1425 non-null   object
 60   Total â€“ Uninsured Population (Asian)                                                1425 non-null   object
 61  Total â€“ Uninsured Population (Native Hawaiian and Other Pacific Islander)            1425 non-null   object
 62   Total â€“ Uninsured Population (HISPANIC OR LATINO, (Some other race)                 1425 non-null   object
 63   Total â€“ Uninsured Population (HISPANIC OR LATINO, (Two or more races)               1425 non-null   object
 64  Total â€“ Uninsured Population (HISPANIC OR LATINO, (of any race)                      1425 non-null   object
 65  Total â€“ Uninsured Population (White)                                                 1425 non-null   object
 66  Percent of Uninsured population                                                      1425 non-null   float64
 67  Percent of Uninsured population - (Male)                                             1425 non-null   float64
 68  Percent of Uninsured population - (Female)                                           1425 non-null   float64
 69  Percent of Uninsured population - (HISPANIC OR LATINO, White)                        1425 non-null   float64
 70  Percent of Uninsured population - (Black or African American)                        1425 non-null   float64
 71  Percent of Uninsured population - (American Indian and Alaska Native)                1425 non-null   float64
 72  Percent of Uninsured population - (Asian)                                            1425 non-null   float64
 73  Percent of Uninsured population - (Native Hawaiian and Other Pacific Islander)       1425 non-null   float64
 74  Percent of Uninsured population - (HISPANIC OR LATINO, (Some other race alone)       1425 non-null   float64
 75  Percent of Uninsured population - (HISPANIC OR LATINO, (Two or more races)           1425 non-null   float64
 76  Percent of Uninsured population - (HISPANIC OR LATINO, (of any race)                 1425 non-null   float64
 77  Percent of Uninsured population - (White)                                            1425 non-null   float64
 78  GEOID                                                                                1425 non-null   object
 79  state                                                                                1425 non-null   float64
 80  county.1                                                                             1425 non-null   float64
dtypes: float64(43), int64(1), object(37)
memory usage: 916.7+ KB

In [17]:
death_coverage.columns = death_coverage.columns.str.strip()

In [64]:
death_coverage1 = death_coverage[['county', 'Age-Adjusted Death Rate', 'Race', 'Total â€“ Insured Population (Female)', 'Total â€“ Uninsured Population (Female)']]

 gourds.replace(to_replace='EXH', value=np.NaN) gourds = gourds.replace(to_replace='DMG', value=np.NaN)

In [65]:
death_coverage1

,county,Age-Adjusted Death Rate,Race,Total â€“ Insured Population (Female),Total â€“ Uninsured Population (Female)
0,Tennessee,21.6,All races,NaN,NaN
1,Tennessee,20.7,White,NaN,NaN
2,Tennessee,29.1,Black,NaN,NaN
3,United States,19.6,All races,NaN,NaN
4,United States,27.6,Black,NaN,NaN
...,...,...,...,...,...
1426,Wayne County,NaN,Black,6456.0,963.0
1427,Wayne County,NaN,Black,6432.0,930.0
1428,Wayne County,NaN,Black,6463.0,889.0
1429,Wayne County,NaN,Black,6476.0,907.0
1430,United States (6),19.7,White,NaN,NaN

In [66]:
death_coverage1 = death_coverage1.replace(to_replace='Tennessee', value=np.NaN)

In [67]:
death_coverage1 = death_coverage1.replace(to_replace='United States', value=np.NaN)

In [68]:
death_coverage1 = death_coverage1.replace(to_replace='United States (6)', value=np.NaN)

In [69]:
death_coverage1

,county,Age-Adjusted Death Rate,Race,Total â€“ Insured Population (Female),Total â€“ Uninsured Population (Female)
0,NaN,21.6,All races,NaN,NaN
1,NaN,20.7,White,NaN,NaN
2,NaN,29.1,Black,NaN,NaN
3,NaN,19.6,All races,NaN,NaN
4,NaN,27.6,Black,NaN,NaN
...,...,...,...,...,...
1426,Wayne County,NaN,Black,6456.0,963.0
1427,Wayne County,NaN,Black,6432.0,930.0
1428,Wayne County,NaN,Black,6463.0,889.0
1429,Wayne County,NaN,Black,6476.0,907.0
1430,NaN,19.7,White,NaN,NaN

In [70]:
death_coverage1.columns = ['county', 'death-rate', 'race','insured_female', 'uninsured_female']
death_coverage1.head()

  county  death-rate       race  insured_female  uninsured_female
0    NaN        21.6  All races             NaN               NaN
1    NaN        20.7      White             NaN               NaN
2    NaN        29.1      Black             NaN               NaN
3    NaN        19.6  All races             NaN               NaN
4    NaN        27.6      Black             NaN               NaN

In [71]:
death_coverage1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1431 entries, 0 to 1430
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   county            1425 non-null   object
 1   death-rate        711 non-null    float64
 2   race              1431 non-null   object
 3   insured_female    1425 non-null   float64
 4   uninsured_female  1425 non-null   float64
dtypes: float64(3), object(2)
memory usage: 67.1+ KB

death_coverage1.groupby(['county']).insured_female.agg({'sum'})

death_coverage1[(death_coverage1['death-rate'] >= 25.0)]

In [72]:
death_cov2 = death_coverage1[(death_coverage1['race'] == 'All races')]
death_cov2

               county  death-rate       race  insured_female  uninsured_female
0                 NaN        21.6  All races             NaN               NaN
3                 NaN        19.6  All races             NaN               NaN
5     Crockett County        31.9  All races          6639.0             659.0
6     Crockett County        31.9  All races          6792.0             644.0
7     Crockett County        31.9  All races          6687.0             766.0
...               ...         ...        ...             ...               ...
1415     Wayne County         NaN  All races          6428.0             980.0
1416     Wayne County         NaN  All races          6456.0             963.0
1417     Wayne County         NaN  All races          6432.0             930.0
1418     Wayne County         NaN  All races          6463.0             889.0
1419     Wayne County         NaN  All races          6476.0             907.0

[477 rows x 5 columns]

In [60]:
death_cov2.groupby(['county']).insured_female.agg({'sum'})

                        sum
county
Anderson County    175695.0
Bedford County     105641.0
Benton County       36289.0
Bledsoe County      27286.0
Blount County      297609.0
...                     ...
Wayne County        32255.0
Weakley County      76683.0
White County        59408.0
Williamson County  526801.0
Wilson County      311921.0

[95 rows x 1 columns]

death_cov2[(death_cov2['race'] == 'All races')]

plt.figure(figsize=(6, 6))

corr = death_coverage1.corr()

# create a custom diverging colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)

# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, cmap=cmap, mask = mask, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5});